# .precommit-config.yaml

repos:
  # Pre-commit hooks for basic code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        description: "Remove trailing whitespace from files"
      - id: end-of-file-fixer
        description: "Ensure files end with a newline"
      - id: check-yaml
        description: "Check YAML files for syntax errors"
      - id: check-added-large-files
        description: "Prevents large files from being added to the repository"

  # Black for automatic code formatting
  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black
        language_version: python3.11
        description: "Automatically formats Python code according to PEP 8"

  # MyPy for static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        description: "Check Python files for type errors"
        additional_dependencies:
          - types-requests

  # isort for automatic import sorting
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort
        description: "Automatically sort imports"
        additional_dependencies:
          - isort[docstrings]  # Optional, if you want to sort docstrings too

# # Run tests as a pre-commit hook using docker-compose
  - repo: local
    hooks:
      - id: run-docker-tests
        name: "Run tests inside Docker"
        entry: "docker-compose run --rm test pytest"
        language: system
        types: [python]
