version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    working_dir: /app
    command: python3 -m pytest -vv  # Command to run tests
    tty: true  # Keep the terminal open, useful for debugging
